### PR TITLE
Fix handling of relative paths

### LINKED ISSUE #316: Passing relative paths to html-report subcommand results in NPE
Hello,

I'm trying to generate html report from xml with command

```bash
java -jar open-test-reporting-cli-0.2.0-M2-standalone.jar \
    html-report --output open-test-report.html junit-platform-events-8096972057150721349.xml hierarchy.xml 
```

but it fails 
```text
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.relativize(java.nio.file.Path)" because the return value of "java.nio.file.Path.getParent()" is null
        at org.opentest4j.reporting.tooling.core.htmlreport.DefaultHtmlReportWriter.tryRelativize(DefaultHtmlReportWriter.java:125)
        at org.opentest4j.reporting.tooling.core.htmlreport.DefaultHtmlReportWriter.extractData(DefaultHtmlReportWriter.java:116)
        at org.opentest4j.reporting.tooling.core.htmlreport.DefaultHtmlReportWriter.writeHtmlReport(DefaultHtmlReportWriter.java:92)
        at org.opentest4j.reporting.cli.HtmlReportCommand.call(HtmlReportCommand.java:69)
        at org.opentest4j.reporting.cli.HtmlReportCommand.call(HtmlReportCommand.java:39)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.opentest4j.reporting.cli.ReportingCli.main(ReportingCli.java:52)



```

### PR DESCRIPTION
**Pull request by marcphilipp**
Fixes #316.

### CODE REVIEW

File: tooling-core/src/main/java/org/opentest4j/reporting/tooling/core/htmlreport/DefaultHtmlReportWriter.java [hunk 1]
```diff
@@ -120,9 +120,13 @@ private List<Execution> extractData(List<Path> xmlFiles, Path htmlFile) throws E
 		return executions;
 	}
 
-	private static Path tryRelativize(Path htmlFile, Path xmlFile) {
+	static Path tryRelativize(Path htmlFile, Path xmlFile) {
 		try {
-			return htmlFile.getParent().relativize(xmlFile);
+			var parent = htmlFile.toAbsolutePath().getParent();
+			if (parent == null) {
+				return xmlFile;
```
Comment (sormuras) [inline tooling-core/src/main/java/org/opentest4j/reporting/tooling/core/htmlreport/DefaultHtmlReportWriter.java:127]:
```suggestion
				return htmlFile;
```

Comment (marcphilipp) [reply tooling-core/src/main/java/org/opentest4j/reporting/tooling/core/htmlreport/DefaultHtmlReportWriter.java:127]: No, we're trying to relativize the XML file and want to fallback on the provided path if we can't.

**Review by sormuras — APPROVED** [review]
